/*********************************************************
 *  Version     Date          Name           Description
 * *******************************************************
 *   V1.0     08-12-2023    Developer1     Add method implemented
 * 
 * *******************************************************/
public with sharing class Calculator {
    public Calculator() {

    }
      public integer add(integer a, integer b){
        return a+b;
      }
}